<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <SonarQubeExclude>false</SonarQubeExclude>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Es.Riam.Gnoss.Util\Es.Riam.Gnoss.Util.csproj" />
    <ProjectReference Include="..\Es.Riam.InterfacesOpenArchivos\Es.Riam.InterfacesOpenArchivos.csproj" />
  </ItemGroup>

</Project>
