<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<SonarQubeExclude>false</SonarQubeExclude>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Es.Riam.Gnoss.AD\Es.Riam.Gnoss.AD.csproj" />
    <ProjectReference Include="..\Es.Riam.Gnoss.CL\Es.Riam.Gnoss.CL.csproj" />
	<ProjectReference Include="..\Es.Riam.Gnoss.Traducciones\Es.Riam.Gnoss.Traducciones.csproj" />
    <ProjectReference Include="..\Es.Riam.Gnoss.Web.LogicaOAuth\Es.Riam.Gnoss.Web.LogicaOAuth.csproj" />
    <ProjectReference Include="..\Es.Riam.Gnoss.Web.OAuthAD\Es.Riam.Gnoss.Web.OAuthAD.csproj" />
  </ItemGroup>

</Project>
