// <auto-generated />
using System;
using Es.Riam.Gnoss.Web.OAuthAD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Es.Riam.Gnoss.Web.OAuthAD.Migrations.OauthOracle
{
    [DbContext(typeof(EntityContextOauthOracle))]
    partial class EntityContextOauthOracleModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.ConsumerData", b =>
                {
                    b.Property<int>("ConsumerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UrlOrigen")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ConsumerId");

                    b.ToTable("ConsumerData");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthConsumer", b =>
                {
                    b.Property<int>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Callback")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("ConsumerKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("ConsumerSecret")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("VerificationCodeFormat")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VerificationCodeLength")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ConsumerId")
                        .HasName("PK_dbo.OAuthConsumer");

                    b.ToTable("OAuthConsumer");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsumerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConsumerVersion")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RequestTokenCallback")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("RequestTokenVerifier")
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB");

                    b.Property<string>("Scope")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("State")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TokenSecret")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid?>("UsuarioID")
                        .HasColumnType("RAW(16)");

                    b.HasKey("TokenId")
                        .HasName("PK_dbo.OAuthToken");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("UsuarioID");

                    b.ToTable("OAuthToken");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthTokenExterno", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("State")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("TokenSecret")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int?>("TokenVinculadoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("RAW(16)");

                    b.HasKey("TokenId");

                    b.HasIndex("UsuarioID");

                    b.ToTable("OAuthTokenExterno");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.PinToken", b =>
                {
                    b.Property<int>("TokenId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("RAW(16)");

                    b.HasKey("TokenId");

                    b.HasIndex("UsuarioID");

                    b.ToTable("PinToken");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("NVARCHAR2(12)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.UsuarioConsumer", b =>
                {
                    b.Property<int>("ConsumerId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("ProyectoID")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("RAW(16)");

                    b.HasKey("ConsumerId")
                        .HasName("PK_Usuario_Consumer");

                    b.HasIndex("UsuarioID");

                    b.ToTable("UsuarioConsumer");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.ConsumerData", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthConsumer", "OAuthConsumer")
                        .WithOne("ConsumerData")
                        .HasForeignKey("Es.Riam.Gnoss.OAuthAD.OAuth.ConsumerData", "ConsumerId")
                        .HasConstraintName("FK_ConsumerData_OAuthConsumer")
                        .IsRequired();

                    b.Navigation("OAuthConsumer");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthToken", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthConsumer", "OAuthConsumer")
                        .WithMany("OAuthToken")
                        .HasForeignKey("ConsumerId")
                        .HasConstraintName("OAuthConsumer_OAuthToken")
                        .IsRequired();

                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.Usuario", "Usuario")
                        .WithMany("OAuthToken")
                        .HasForeignKey("UsuarioID")
                        .HasConstraintName("FK_OAuthToken_Usuario");

                    b.Navigation("OAuthConsumer");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthTokenExterno", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthToken", "OAuthToken")
                        .WithOne("OAuthTokenExterno")
                        .HasForeignKey("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthTokenExterno", "TokenId")
                        .HasConstraintName("FK_OAuthTokenExterno_OAuthToken")
                        .IsRequired();

                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.Usuario", "Usuario")
                        .WithMany("OAuthTokenExterno")
                        .HasForeignKey("UsuarioID")
                        .HasConstraintName("FK_OAuthTokenExterno_Usuario")
                        .IsRequired();

                    b.Navigation("OAuthToken");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.PinToken", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthToken", "OAuthToken")
                        .WithOne("PinToken")
                        .HasForeignKey("Es.Riam.Gnoss.OAuthAD.OAuth.PinToken", "TokenId")
                        .HasConstraintName("FK_PinToken_OAuthToken")
                        .IsRequired();

                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.Usuario", "Usuario")
                        .WithMany("PinToken")
                        .HasForeignKey("UsuarioID")
                        .HasConstraintName("FK_PinToken_Usuario")
                        .IsRequired();

                    b.Navigation("OAuthToken");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.UsuarioConsumer", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthConsumer", "OAuthConsumer")
                        .WithOne("UsuarioConsumer")
                        .HasForeignKey("Es.Riam.Gnoss.OAuthAD.OAuth.UsuarioConsumer", "ConsumerId")
                        .HasConstraintName("FK_Usuario_Consumer_OAuthConsumer")
                        .IsRequired();

                    b.HasOne("Es.Riam.Gnoss.OAuthAD.OAuth.Usuario", "Usuario")
                        .WithMany("UsuarioConsumer")
                        .HasForeignKey("UsuarioID")
                        .HasConstraintName("FK_Usuario_Consumer_Usuario")
                        .IsRequired();

                    b.Navigation("OAuthConsumer");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthConsumer", b =>
                {
                    b.Navigation("ConsumerData");

                    b.Navigation("OAuthToken");

                    b.Navigation("UsuarioConsumer");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.OAuthToken", b =>
                {
                    b.Navigation("OAuthTokenExterno");

                    b.Navigation("PinToken");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.OAuthAD.OAuth.Usuario", b =>
                {
                    b.Navigation("OAuthToken");

                    b.Navigation("OAuthTokenExterno");

                    b.Navigation("PinToken");

                    b.Navigation("UsuarioConsumer");
                });
#pragma warning restore 612, 618
        }
    }
}
