//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Riam.Gnoss.FirstDataLoad.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Riam.Gnoss.FirstDataLoad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N&apos;Comentario&apos;, N&apos;dce:type&apos;, N&apos;Espacio@es|||Space@en&apos;, 2, 1, 0, 1, 5, 8, 0, 2, 1, N&apos;Espacio@es|||Space@en&apos;, 0)
        ///
        ///INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropied [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string carga_bd_acid_facetaobjetoconocimiento {
            get {
                return ResourceManager.GetString("carga_bd_acid_facetaobjetoconocimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT [dbo].[Pais] ([PaisID], [Nombre]) VALUES (N&apos;99a26e3a-16b5-4321-8ef3-016dbd925c59&apos;, N&apos;Samoa&apos;)
        ///INSERT [dbo].[Pais] ([PaisID], [Nombre]) VALUES (N&apos;12efc107-5c37-4269-8bf8-019f2e9a2d02&apos;, N&apos;Kiribati&apos;)
        ///INSERT [dbo].[Pais] ([PaisID], [Nombre]) VALUES (N&apos;0e8cf3f7-154b-4fdd-98df-04cb26786af1&apos;, N&apos;Gabón&apos;)
        ///INSERT [dbo].[Pais] ([PaisID], [Nombre]) VALUES (N&apos;e5a21c0b-98d2-4ea1-a074-05544c803f77&apos;, N&apos;Fiyi&apos;)
        ///INSERT [dbo].[Pais] ([PaisID], [Nombre]) VALUES (N&apos;7fe46ca5-6440-4f3c-8330-0584ee70ba12&apos;, N&apos;Islas Vírgenes [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string carga_bd_acid_pais {
            get {
                return ResourceManager.GetString("carga_bd_acid_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT [dbo].[Provincia] ([ProvinciaID], [PaisID], [Nombre], [CP]) VALUES (N&apos;df9d1c7e-de78-474c-b931-0011cb9655b3&apos;, N&apos;98d604b4-3141-4499-bde1-c320f09ef45c&apos;, N&apos;Murcia&apos;, N&apos;30&apos;)
        ///INSERT [dbo].[Provincia] ([ProvinciaID], [PaisID], [Nombre], [CP]) VALUES (N&apos;bd4dbd91-b048-41e3-bebe-00484966cde8&apos;, N&apos;98d604b4-3141-4499-bde1-c320f09ef45c&apos;, N&apos;Burgos&apos;, N&apos;09&apos;)
        ///INSERT [dbo].[Provincia] ([ProvinciaID], [PaisID], [Nombre], [CP]) VALUES (N&apos;c5460d7d-7aa0-409b-a3c0-0587aa40c0a6&apos;, N&apos;98d604b4-3141-4499-bde1-c320f09ef45c&apos;, N&apos;A [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string carga_bd_acid_provincia {
            get {
                return ResourceManager.GetString("carga_bd_acid_provincia", resourceCulture);
            }
        }
    }
}
