//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Riam.Gnoss.AD.ServiciosGenerales.EntityModel
{
    public partial class PermisosPaginasUsuarios
    {
        public System.Guid UsuarioID { get; set; }
        public System.Guid OrganizacionID { get; set; }
        public System.Guid ProyectoID { get; set; }
        public short Pagina { get; set; }
    }
}
