// <auto-generated />
using System;
using Es.Riam.Gnoss.AD.EntityModelBASE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace Es.Riam.Gnoss.AD.Migrations.EntityContextBASEOracleMigrations
{
    [DbContext(typeof(EntityContextBASEOracle))]
    partial class EntityContextBASEOracleModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreo", b =>
                {
                    b.Property<int>("CorreoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DireccionRespuesta")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<bool>("EnviadoRabbit")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("EsHtml")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("EsSeguro")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("FechaPuestaEnCola")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("HtmlTexto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MascaraDireccionRespuesta")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("MascaraRemitente")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<short>("Prioridad")
                        .HasColumnType("NUMBER(5)");

                    b.Property<int>("Puerto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("SMTP")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(10)");

                    b.HasKey("CorreoID");

                    b.ToTable("ColaCorreo");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreoDestinatario", b =>
                {
                    b.Property<int>("CorreoID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<short>("Estado")
                        .HasColumnType("NUMBER(5)");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("MascaraDestinatario")
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.HasKey("CorreoID", "Email");

                    b.ToTable("ColaCorreoDestinatario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreoDestinatario", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreo", "ColaCorreo")
                        .WithMany("ColaCorreoDestinatario")
                        .HasForeignKey("CorreoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ColaCorreo");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreo", b =>
                {
                    b.Navigation("ColaCorreoDestinatario");
                });
#pragma warning restore 612, 618
        }
    }
}
