//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Riam.Gnoss.Elementos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Riam.Gnoss.Elementos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Modificacions al dafo ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Hola {#NombrePersona#},{/p}{p}el dafo ‘{#NombreDafo#}’ en el qual participes compta amb una novetat que pot ser del teu interès.{/p}{p}El factor:{/br} {#Texto#} {/br} s&apos;ha modificat i el seu nou contingut és: {/br} {#Texto2#} {/br}.{/p}{p}Si ho desitges, pots accedir al {a href=&quot;{#UrlEnlace#}&quot;}dafo{/a} i votar, comentar o afegir factors.{/p}{p}Gaudeix de {#NombreEcosistema#}; nosaltr [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_ca {
            get {
                return ResourceManager.GetString("Mensajes_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///	&lt;mensajes&gt;
        ///		&lt;mensaje id=&quot;0&quot;&gt;
        ///			&lt;asunto&gt;Modificacions al dafo &apos;{#NombreDafo#}&apos;&lt;/asunto&gt;
        ///			&lt;texto&gt;{p}Hola {#NombrePersona#},{/p}{p}el dafo &apos;{#NombreDafo#}&apos; en el qual participes compta amb una novetat que pot ser del teu interés.{/p}{p}El factor:{/br} {#Texto#} {/br} s&apos;ha modificat i el seu nou contingut és: {/br} {#Texto2#} {/br}.{/p}{p}Si ho desitges, pots accedir al {a href=&quot;{#UrlEnlace#}&quot;}dafo{/a} i votar, comentar o afegir factors.{/p}{p}Gaudeix de {#NombreEcosistema#}; nosaltres innove [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_ca_valencia {
            get {
                return ResourceManager.GetString("Mensajes_ca_valencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Änderungen in der SWOT ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Hallo {#NombrePersona#},{/p}{p} dii SWOT ‘{#NombreDafo#}’ an der du teilnimmst, hat eine interessante Neuigkeit für dich.{/p}{p}Der Fakor:{/br} {#Texto#} {/br} wurde verändert und sein neuer Inhalt ist: {/br} {#Texto2#} {/br}.{/p}{p}Wenn du möchtest, erhältst du Zugriff auf {a href=&quot;{#UrlEnlace#}&quot;}dafo{/a} um zu wählen, zu kommentieren oder Faktoren hinzuzufügen.{/p}{p}Erfreue dich  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_de {
            get {
                return ResourceManager.GetString("Mensajes_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///  &lt;mensaje id=&quot;0&quot;&gt;
        ///  &lt;asunto&gt;Modifications in the SWOT ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///    &lt;texto&gt;{p}Hello {#NombrePersona#},{/p}{p}the SWOT analysis ‘{#NombreDafo#}’ you&apos;re taking part in has some news that may interest you.{/p}{p}The factor:{/br} {#Texto#} {/br} was modified and its new content is: {/br} {#Texto2#} {/br}.{/p}{p}If you want, you can access the {a href=&quot;{#UrlEnlace#}&quot;}SWOT analysis{/a} and vote, comment or add factors.{/p}{p}Enjoy {#NombreEcosistema#}; we innovate with  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_en {
            get {
                return ResourceManager.GetString("Mensajes_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;35&quot;&gt;
        ///      &lt;asunto&gt;You can already work with your class in {#NombreEcosistema#}&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Hello {#NombrePersona#},{/p}{p}Congratulations!Your request for the class {#NombreOrganizacion#} and the community {#NombreProyecto#} was accepted. To start working now, we recommend that you go directly to your {a href=&quot;{#Texto#}&quot; target=&quot;_blank&quot;}classes{/a} or {a href=&quot;{#Texto2#}&quot; target=&quot;_blank&quot;}communities{/a} and start the management inviting your students [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_en_personalizado {
            get {
                return ResourceManager.GetString("Mensajes_en_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Modificaciones en el dafo ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Hola {#NombrePersona#},{/p}{p}el dafo ‘{#NombreDafo#}’ en el que participas cuenta con una novedad que puede ser de tu interés.{/p}{p}El factor:{/br} {#Texto#} {/br} se ha modificado y su nuevo contenido es: {/br} {#Texto2#} {/br}.{/p}{p}Si lo deseas, puedes acceder al {a href=&quot;{#UrlEnlace#}&quot;}dafo{/a} y votar, comentar o añadir factores.{/p}{p}Disfruta de {#NombreEcosistema#}; no [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_es {
            get {
                return ResourceManager.GetString("Mensajes_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;35&quot;&gt;
        ///      &lt;asunto&gt;Ya puedes trabajar con tu clase en {#NombreEcosistema#}&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Hola {#NombrePersona#},{/p}{p}¡Enhorabuena! Tu solicitud de la clase {#NombreOrganizacion#} y de la comunidad {#NombreProyecto#} ha sido aceptada. Para comenzar a trabajar ya, te recomendamos acceder directamente a tus {a href=&quot;{#Texto#}&quot; target=&quot;_blank&quot;}clases{/a} o {a href=&quot;{#Texto2#}&quot; target=&quot;_blank&quot;}comunidades{/a} e iniciar su administración invitando a tus alu [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_es_personalizado {
            get {
                return ResourceManager.GetString("Mensajes_es_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Aldaketak dafoan ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Kaixo {#NombrePersona#},{/p}{p}parte hartzen ari zaren ‘{#NombreDafo#}’ dafoak zure interesekoa izan daitekeen berritasun bat du.{/p}{p}Faktorea:{/br} {#Texto#} {/br} aldatu egin da eta bere eduki berria honako hau da: {/br} {#Texto2#} {/br}.{/p}{p}Nahi baduzu, {a href=&quot;{#UrlEnlace#}&quot;}dafora{/a} sar zaitezke eta bozkatu, aipamenak egin edo faktoreak gehi ditzakezu.{/p}{p}Gozatu {#NombreEc [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_eu {
            get {
                return ResourceManager.GetString("Mensajes_eu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Modifications dans le SWOT ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Bonjour {#NombrePersona#},{/p}{p}le SWOT ‘{#NombreDafo#}’ auquel vous participez dispose d’une nouveauté susceptible de vous intéresser.{/p}{p}Le facteur :{/br} {#Texto#} {/br} a été modifié et son nouveau contenu est : {/br} {#Texto2#} {/br}.{/p}{p}Si vous le souhaitez, vous pouvez accéder au {a href=&quot;{#UrlEnlace#}&quot;}SWOT{/a} et voter, faire un commentaire ou ajouter des facteur [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_fr {
            get {
                return ResourceManager.GetString("Mensajes_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Modificacións no dafo ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Ola {#NombrePersona#},{/p}{p}o dafo ‘{#NombreDafo#}’ no que participas conta cunha novidade que pode ser do teu interese.{/p}{p}O factor:{/br} {#Texto#} {/br} modificouse e o seu novo contido é: {/br} {#Texto2#} {/br}.{/p}{p}Se o desexas, podes acceder ao {a href=&quot;{#UrlEnlace#}&quot;}dafo{/a} e votar, comentar ou engadir factores.{/p}{p}Goza de {#NombreEcosistema#}; nós innovamos contigo. [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_gl {
            get {
                return ResourceManager.GetString("Mensajes_gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///      &lt;asunto&gt;Modifiche nella swoft ‘{#NombreDafo#}’&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Ciao {#NombrePersona#},{/p}{p}la swot ‘{#NombreDafo#}’ a cui partecipi ha una novità che ti potrebbe interessare.{/p}{p}Il fattore:{/br} {#Texto#} {/br} è stato  modificato e il suo nuovo contenuto è: {/br} {#Texto2#} {/br}.{/p}{p}Se preferisci, puoi accedere alla {a href=&quot;{#UrlEnlace#}&quot;}swot{/a} e votare, commentare o aggiungere fattori.{/p}{p}Godi di {#NombreEcosistema#}; innoviamo [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_it {
            get {
                return ResourceManager.GetString("Mensajes_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;0&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;1&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;2&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;3&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;4&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;5&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;6&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;7&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;8&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;9&quot;&gt;
        ///    &lt;/mensaje&gt;
        ///    &lt;mensaje id=&quot;20&quot;&gt;
        ///      &lt;asunto&gt;Solicitacao de acesso a comunidade &quot;{#NombreProyecto#}&quot;&lt;/asunto&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_pt {
            get {
                return ResourceManager.GetString("Mensajes_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;correos&gt;
        ///  &lt;mensajes&gt;
        ///    &lt;mensaje id=&quot;35&quot;&gt;
        ///      &lt;asunto&gt;Ja se pode trabalhar com a sua classe em {#NombreEcosistema#}&lt;/asunto&gt;
        ///      &lt;texto&gt;{p}Ola {#NombrePersona#},{/p}{p}Parabéns! Sua solicitação de classe {#NombreOrganizacion#} e da comunidade {#NombreProyecto#} foi aceita. Para iniciar a trabalhar, te recomendamos acceder directamente a tus {a href=&quot;{#Texto#}&quot; target=&quot;_blank&quot;}clases{/a} o {a href=&quot;{#Texto2#}&quot; target=&quot;_blank&quot;}comunidades{/a} e iniciar su administración invitando a tus alumnos a su [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Mensajes_pt_personalizado {
            get {
                return ResourceManager.GetString("Mensajes_pt_personalizado", resourceCulture);
            }
        }
    }
}
