//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Riam.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Riam.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about
        ///1
        ///after
        ///2
        ///all
        ///also
        ///3
        ///an
        ///4
        ///and
        ///5
        ///another
        ///6
        ///any
        ///7
        ///are
        ///8
        ///as
        ///9
        ///at
        ///0
        ///a
        ///b
        ///c
        ///d
        ///e
        ///f
        ///g
        ///h
        ///i
        ///j
        ///k
        ///l
        ///m
        ///n
        ///o
        ///p
        ///q
        ///r
        ///s
        ///t
        ///u
        ///v
        ///w
        ///x
        ///y
        ///z
        ///be
        ///$
        ///because
        ///been
        ///before
        ///being
        ///between
        ///both
        ///but
        ///by
        ///came
        ///can
        ///come
        ///consequently
        ///could
        ///did
        ///do
        ///does
        ///each
        ///else
        ///finally
        ///for
        ///from
        ///furthermore
        ///get
        ///got
        ///has
        ///had
        ///he
        ///hence
        ///have
        ///her
        ///here
        ///him
        ///himself
        ///his
        ///how
        ///however
        ///if
        ///in
        ///into
        ///is
        ///it
        ///its
        ///just
        ///like
        ///make
        ///many
        ///me
        ///might
        ///more
        ///moreover
        ///most
        ///much
        ///must
        ///my
        ///nev [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string noiseENG {
            get {
                return ResourceManager.GetString("noiseENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C
        ///1
        ///D
        ///2
        ///I
        ///3
        ///4
        ///5
        ///6
        ///7
        ///L
        ///8
        ///M
        ///9
        ///a
        ///b
        ///c
        ///d
        ///e
        ///f
        ///g
        ///h
        ///i
        ///j
        ///k
        ///l
        ///m
        ///n
        ///o
        ///p
        ///q
        ///r
        ///s
        ///t
        ///u
        ///v
        ///w
        ///x
        ///y
        ///z
        ///Ud.
        ///0
        ///Uds.
        ///$
        ///Vd.
        ///Vds.
        ///XI
        ///XII
        ///XIII
        ///XIV
        ///XIX
        ///XL
        ///XLI
        ///XLII
        ///XLIII
        ///XLIV
        ///XLIX
        ///XLV
        ///XLVI
        ///XLVII
        ///XLVIII
        ///XV
        ///XVI
        ///XVII
        ///XVIII
        ///XX
        ///XXI
        ///XXII
        ///XXIII
        ///XXIV
        ///XXIX
        ///XXV
        ///XXVI
        ///XXVII
        ///XXVIII
        ///XXX
        ///XXXI
        ///XXXII
        ///XXXIII
        ///XXXIV
        ///XXXIX
        ///XXXV
        ///XXXVI
        ///XXXVII
        ///XXXVIII
        ///a
        ///ab
        ///abajo
        ///acerca
        ///adelante
        ///además
        ///adentro
        ///adiós
        ///adonde
        ///adónde
        ///afuera
        ///ah
        ///ahora
        ///ajá
        ///al
        ///albricias
        ///ale
        ///aleluya
        ///al [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string noiseESN {
            get {
                return ResourceManager.GetString("noiseESN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a
        ///b
        ///c
        ///d
        ///e
        ///f
        ///g
        ///h
        ///i
        ///j
        ///k
        ///l
        ///m
        ///n
        ///o
        ///p
        ///q
        ///r
        ///s
        ///t
        ///u
        ///v
        ///w
        ///x
        ///y
        ///z
        ///zenbat
        ///batzuk
        ///zenbait
        ///asko
        ///gutxi
        ///anitz
        ///hagitz
        ///franko
        ///honenbeste
        ///hainbat
        ///ugari
        ///dezente
        ///nahiko(a)
        ///aski
        ///pilo bat
        ///mordo bat
        ///makina bat
        ///apur bat
        ///pixka bat
        ///pittin bat
        ///alajaina
        ///alajainkoa
        ///alazankoa
        ///alafede
        ///arranopola
        ///arraio
        ///arraioak ez baditu
        ///nola arraio
        ///nola demontre
        ///nola demonio
        ///kontxo
        ///demontre
        ///zer demontre
        ///joã±o
        ///jo
        ///ã‘o
        ///motel
        ///agian bai
        ///agian ez
        ///ah
        ///ai ene
        ///ai ama
        ///ai
        ///aitaren eta semearen…
        ///ala
        ///a [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string noiseEUSK {
            get {
                return ResourceManager.GetString("noiseEUSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a
        ///b
        ///c
        ///d
        ///e
        ///f
        ///g
        ///h
        ///i
        ///j
        ///k
        ///l
        ///m
        ///n
        ///o
        ///p
        ///q
        ///r
        ///s
        ///t
        ///u
        ///v
        ///w
        ///x
        ///y
        ///z
        ///abaixo
        ///perto
        ///avançar
        ///também
        ///em
        ///adeus
        ///onde
        ///onde
        ///fora
        ///agora
        ///ao
        ///boa notícia
        ///aleluia
        ///algo
        ///alguém
        ///alguma
        ///algumas 
        ///algum
        ///alguns
        ///algum
        ///alta
        ///alto
        ///ambas
        ///ambos 
        ///andar
        ///antes
        ///antes
        ///que
        ///aquela
        ///que
        ///que
        ///aqueles
        ///que
        ///aquela
        ///aquelas
        ///aquelos
        ///acima
        ///assim
        ///mesmo
        ///embora
        ///baixo
        ///suficiente
        ///bastante
        ///bastantes
        ///bem
        ///billionéssima
        ///billionéssimas
        ///billionéssimo
        ///billionéssimos
        ///bilhão
        ///ser
        ///cada
        ///caramba
        ///puxa
        ///catap [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string noisePOR {
            get {
                return ResourceManager.GetString("noisePOR", resourceCulture);
            }
        }
    }
}
