//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Riam.Gnoss.Recursos.Properties {
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Riam.Gnoss.Recursos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Catalan&quot; code=&quot;ca&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Recursos&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Añadir nueva newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Invita els teus amics a la teva xarxa de contactes a @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Digues-nos en quines categories de l&apos;índex global de @1@ vols que trobin la teva comunitat&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;TEXTOAGRE [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;config&gt;
        ///	&lt;ConfiguracionGeneral&gt;
        ///		&lt;idiomasOnto&gt;
        ///			&lt;idiomaOnto&gt;es&lt;/idiomaOnto&gt;
        ///		&lt;/idiomasOnto&gt;
        ///	&lt;/ConfiguracionGeneral&gt;
        ///	&lt;EspefPropiedad&gt;
        ///		&lt;Propiedad ID=&quot;PersonName&quot; EntidadID=&quot;CandidatePerson&quot;&gt;
        ///			&lt;AtrNombre&gt;Nombre&lt;/AtrNombre&gt;
        ///			&lt;AtrNombreLectura&gt;Nombre&lt;/AtrNombreLectura&gt;
        ///      &lt;CampoDeshabilitado&gt;&lt;/CampoDeshabilitado&gt;
        ///		&lt;/Propiedad&gt;
        ///    &lt;Propiedad ID=&quot;FatherName&quot; EntidadID=&quot;CandidatePerson&quot;&gt;
        ///      &lt;AtrNombre&gt;Apellidos&lt;/AtrNombre&gt;
        ///      &lt;AtrNombreLectura&gt;Apellidos&lt;/AtrNombreLectura&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Curriculum {
            get {
                return ResourceManager.GetString("Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] DC {
            get {
                object obj = ResourceManager.GetObject("DC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;German&quot; code=&quot;de&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Ressourcen&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Neuen Newsletter hinzufügen&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Lade deine Freunde zu deinem Netzwerk aus Kontakten bei @1@ ein&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;In welcher Kategorie des allgemeinen Verzeichnisses von @1@ soll deine Gemeinde erscheinen?&lt;/Resource&gt;
        ///    &lt;Resource t [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;English&quot; code=&quot;en&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Resources&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Add a new newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Invite your friends to your contact network on @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Tell us in which categories of the @1@ global index you want your community to be found&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;TEXTOAGREGARTWITTER&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Resources language=&quot;English&quot; code=&quot;en&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;NUEVAFUNCIONALIDAD&quot;&gt;
        ///      {p}{/p}Hi {span style=&quot;color:orange;&quot;}gnossonaut{/span}!{p}{/p}{p}{/p}
        ///      Welcome to the new gnoss.com design. We have good news. The experience on gnoss.com has changed with the new navigation.{p}{/p}{p}{/p}
        ///      Do you want to know this changes?{p}{/p}
        ///    &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;INICIOENLACE&quot;&gt;http://gnoss.com/en/home&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;LINKAYUD [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string en_personalizado {
            get {
                return ResourceManager.GetString("en_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Spanish&quot; code=&quot;es&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;CRITERIOBUSQUEDA&quot;&gt;Criterio de busqueda&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Recursos&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Añadir nueva newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Invita a tus amigos a tu red de contactos en @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Dinos en qué categorías del índice global de @1@ quieres que encuentr [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Resources language=&quot;Spanish&quot; code=&quot;es&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;NUEVAFUNCIONALIDAD&quot;&gt;
        ///      {p}{/p}¡Hola {span style=&quot;color:orange;&quot;}gnossonauta{/span}!{p}{/p}{p}{/p}
        ///      Bienvenido de nuevo a gnoss.com. Tenemos buenas noticias. La experiencia de navegación en gnoss.com cambia con nuestro nuevo diseño.{p}{/p}{p}{/p}
        ///      ¿Quieres conocer las novedades?{p}{/p}
        ///    &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;INICIOENLACE&quot;&gt;http://gnoss.com/home&lt;/Resource&gt;
        ///    &lt;Resource ta [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string es_personalizado {
            get {
                return ResourceManager.GetString("es_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Basque&quot; code=&quot;eu&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;CRITERIOBUSQUEDA&quot;&gt;Bilaketa egiteko irizpidea&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Baliabideak&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Añadir nueva newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Gonbidatu zuren lagunak zure harremanen sarera @1@(e)n&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Esan iezaguzu @1@(a)ren aurkibide orokorraren zein kate [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string eu {
            get {
                return ResourceManager.GetString("eu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] foaf_20100101 {
            get {
                object obj = ResourceManager.GetObject("foaf_20100101", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;French&quot; code=&quot;fr&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Ressources&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Ajouter une nouvelle newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Invitez vos amis à rejoindre votre réseau de contacts sur @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Dites-nous dans quelle catégorie du sommaire global de @1@ souhaitez-vous que l’on trouve votre communauté&lt;/Resource&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Galician&quot; code=&quot;gl&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Recursos&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Añadir nueva newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Invita os teus amigos á túa rede de contactos en @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Dinos en que categorías do índice global de @1@ queres que atopen a túa comunidade&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;TEXTOAGREGARTWITTER&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string gl {
            get {
                return ResourceManager.GetString("gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Italian&quot; code=&quot;it&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Risorse&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Aggiungi nuova newsletter&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Invita i tuoi amici alla tua rete di contatti su @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Segnalaci quali categorie dell&apos;indice generale di @1@ vuoi trovare nella tua comunità&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;TEXTOAGREGARTWITT [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ns {
            get {
                object obj = ResourceManager.GetObject("ns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ontologia {
            get {
                object obj = ResourceManager.GetObject("ontologia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Portuguese&quot; code=&quot;pt&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;BASERECURSOS&quot;&gt;Recursos&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;SUBIRNEWSLETTER&quot;&gt;Adicionar um novo boletim&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;MODULOCONTACTOS&quot;&gt;Convidar a um amigo para a rede de contatos de @1@&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;ADMINCOMTEXTOCATEGORIAS&quot;&gt;Conte-nos em que categoria do indice Global de @1@ quer encontrar sua comunidade? &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;TEXTOAGREGARTWITTE [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Resources language=&quot;Portuguese&quot; code=&quot;pt&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;NUEVAFUNCIONALIDAD&quot;&gt;
        ///      {p}{/p}¡Hola {span style=&quot;color:orange;&quot;}gnossonauta{/span}!{p}{/p}{p}{/p}
        ///      Bienvenido de Novos a gnoss.com. Tenemos buenas noticias. La experiencia de navegación en gnoss.com cambia con nuestro Novos diseño.{p}{/p}{p}{/p}
        ///      ¿Quieres conocer las Novidades?{p}{/p}
        ///    &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;INICIOENLACE&quot;&gt;http://gnoss.com/Inicial&lt;/Resource&gt;
        ///    &lt;Resou [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string pt_personalizado {
            get {
                return ResourceManager.GetString("pt_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] rdf {
            get {
                object obj = ResourceManager.GetObject("rdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] skos {
            get {
                object obj = ResourceManager.GetObject("skos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] types {
            get {
                object obj = ResourceManager.GetObject("types", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
