//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Riam.Gnoss.Recursos.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Riam.Gnoss.Recursos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Catalan&quot; code=&quot;ca&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Data de creació&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Veure més comentaris&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Desplegar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Plegar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Carregant...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualitzar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;SICONTINUASDESACTIVARASELREGISTROAUTOMATICOPARAESTACOMUNIDA&quot;&gt;S [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Resources language=&quot;Valencian&quot; code=&quot;ca-valencia&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Veure els resultats de: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Data de creació&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Veure més comentaris&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Desplegar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Plegar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Carregant...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visu [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ca_valencia {
            get {
                return ResourceManager.GetString("ca_valencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;config&gt;
        ///	&lt;ConfiguracionGeneral&gt;
        ///		&lt;idiomasOnto&gt;
        ///			&lt;idiomaOnto&gt;es&lt;/idiomaOnto&gt;
        ///		&lt;/idiomasOnto&gt;
        ///	&lt;/ConfiguracionGeneral&gt;
        ///	&lt;EspefPropiedad&gt;
        ///		&lt;Propiedad ID=&quot;PersonName&quot; EntidadID=&quot;CandidatePerson&quot;&gt;
        ///			&lt;AtrNombre&gt;Nombre&lt;/AtrNombre&gt;
        ///			&lt;AtrNombreLectura&gt;Nombre&lt;/AtrNombreLectura&gt;
        ///      &lt;CampoDeshabilitado&gt;&lt;/CampoDeshabilitado&gt;
        ///		&lt;/Propiedad&gt;
        ///    &lt;Propiedad ID=&quot;FatherName&quot; EntidadID=&quot;CandidatePerson&quot;&gt;
        ///      &lt;AtrNombre&gt;Apellidos&lt;/AtrNombre&gt;
        ///      &lt;AtrNombreLectura&gt;Apellidos&lt;/AtrNombreLectura&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string Curriculum {
            get {
                return ResourceManager.GetString("Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] DC {
            get {
                object obj = ResourceManager.GetObject("DC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;German&quot; code=&quot;de&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Ergebnisse anzeigen für: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Datum der Erstellung&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Weitere Kommentare anzeigen&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Entfalten&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Falten&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Laden...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualis [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;English&quot; code=&quot;en&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;See results for: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Date of creation&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;See more comments&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Unfold&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Fold&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Loading...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualize&lt;/Resource&gt;
        ///		&lt;Resourc [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Resources language=&quot;English&quot; code=&quot;en&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;NUEVAFUNCIONALIDAD&quot;&gt;
        ///      {p}{/p}Hi {span style=&quot;color:orange;&quot;}gnossonaut{/span}!{p}{/p}{p}{/p}
        ///      Welcome to the new gnoss.com design. We have good news. The experience on gnoss.com has changed with the new navigation.{p}{/p}{p}{/p}
        ///      Do you want to know this changes?{p}{/p}
        ///    &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;INICIOENLACE&quot;&gt;http://gnoss.com/en/home&lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;LINKAYUD [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string en_personalizado {
            get {
                return ResourceManager.GetString("en_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Spanish&quot; code=&quot;es&quot;&gt;		
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Ver los resultados de: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Fecha de creación&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Ver más comentarios&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Desplegar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Plegar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Cargando...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualizar&lt;/Res [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Resources language=&quot;Spanish&quot; code=&quot;es&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;NUEVAFUNCIONALIDAD&quot;&gt;
        ///      {p}{/p}¡Hola {span style=&quot;color:orange;&quot;}gnossonauta{/span}!{p}{/p}{p}{/p}
        ///      Bienvenido de nuevo a gnoss.com. Tenemos buenas noticias. La experiencia de navegación en gnoss.com cambia con nuestro nuevo diseño.{p}{/p}{p}{/p}
        ///      ¿Quieres conocer las novedades?{p}{/p}
        ///    &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;INICIOENLACE&quot;&gt;http://gnoss.com/home&lt;/Resource&gt;
        ///    &lt;Resource ta [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string es_personalizado {
            get {
                return ResourceManager.GetString("es_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Basque&quot; code=&quot;eu&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Emaitzak ikusi honetarako: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Sortze data&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Ikusi iruzkin gehiago&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Zabaldu&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Tolestu&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Kargatzen…&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Ikusi&lt;/Resource&gt;
        ///		 [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string eu {
            get {
                return ResourceManager.GetString("eu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] foaf_20100101 {
            get {
                object obj = ResourceManager.GetObject("foaf_20100101", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;French&quot; code=&quot;fr&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Voir les résultats pour : &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Date de création&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Voir plus de commentaires&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Déplier&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Plier&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Chargement...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualiser&lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Galician&quot; code=&quot;gl&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Ver os resultados de: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Data de creación&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Ver máis comentarios&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Despregar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Dobrar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Cargando...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualizar&lt;/Resou [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string gl {
            get {
                return ResourceManager.GetString("gl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Italian&quot; code=&quot;it&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Vedi i risultati per: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Data di creazione&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Vedi altri commenti&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Spiegare&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Piegare&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;CARGANDO&quot;&gt;Caricamento...&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VISUALIZAR&quot;&gt;Visualizzare&lt;/R [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ns {
            get {
                object obj = ResourceManager.GetObject("ns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ontologia {
            get {
                object obj = ResourceManager.GetObject("ontologia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Resources language=&quot;Portuguese&quot; code=&quot;pt&quot;&gt;
        ///	&lt;page name=&quot;COMMON&quot;&gt;
        ///		&lt;Resource tag=&quot;TEXTOAUTOCOMPLETAROPCIONDEFECTO&quot;&gt;Ver os resultados de: &lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;FECHACREACION&quot;&gt;Data de criação&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESPLEGAR&quot;&gt;Implantar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;PLEGAR&quot;&gt;Dobrar&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;VERMASCOMENTARIOS&quot;&gt;Ver mais comentários&lt;/Resource&gt;
        ///		&lt;Resource tag=&quot;DESEASELIMINARELMENSAJESELECCIONADO&quot;&gt;Queres eliminar a mensaxe seleccionada?&lt;/R [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Resources language=&quot;Portuguese&quot; code=&quot;pt&quot;&gt;
        ///  &lt;page name=&quot;COMMON&quot;&gt;
        ///    &lt;Resource tag=&quot;NUEVAFUNCIONALIDAD&quot;&gt;
        ///      {p}{/p}¡Hola {span style=&quot;color:orange;&quot;}gnossonauta{/span}!{p}{/p}{p}{/p}
        ///      Bienvenido de Novos a gnoss.com. Tenemos buenas noticias. La experiencia de navegación en gnoss.com cambia con nuestro Novos diseño.{p}{/p}{p}{/p}
        ///      ¿Quieres conocer las Novidades?{p}{/p}
        ///    &lt;/Resource&gt;
        ///    &lt;Resource tag=&quot;INICIOENLACE&quot;&gt;http://gnoss.com/Inicial&lt;/Resource&gt;
        ///    &lt;Resou [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string pt_personalizado {
            get {
                return ResourceManager.GetString("pt_personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] rdf {
            get {
                object obj = ResourceManager.GetObject("rdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] skos {
            get {
                object obj = ResourceManager.GetObject("skos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] types {
            get {
                object obj = ResourceManager.GetObject("types", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
