INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentario', N'dce:type', N'Espacio@es|||Space@en', 2, 1, 0, 1, 5, 8, 0, 2, 1, N'Espacio@es|||Space@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentario', N'gnoss:Leido', N'Estado@es|||Status@en', 1, 0, 0, 1, 5, 8, 0, 0, 1, N'Estado@es|||Status@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en debates', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en preguntas', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comentarios en recursos', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'gnoss:hasAdministrador', N'Administradores y supervisores@es|||Manager@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Administradores y supervisores@es|||Manager@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'gnoss:hasfechaAlta', N'Fecha de alta@es|||Date of registration@en', 0, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de alta@es|||Date of registration@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'gnoss:hasnumerorecursos', N'Número de recursos@es|||Number of resources@en', 10005, 0, 0, 3, 5, 9, 0, 0, 1, N'Número de recursos@es|||Number of resources@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'gnoss:TipoAcceso', N'Tipo de acesso: @es|||Access type: @en', 10006, 0, 0, 1, 5, 8, 0, 0, 1, N'Tipo de acesso: @es|||Access type: @en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 0, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 2, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Comunidad', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contactos', N'rdf:type', N'Tipos de contacto@es|||Contact type@en', 1, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipos de contacto@es|||Contact type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contactos', N'sioc:has_space', N'Comunidades@es|||Communities@en', 2, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Debates', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Contribuciones en Recursos', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Debate', N'gnoss:hasestado', N'Estado@es|||State@en', 10006, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Debate', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10005, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Debate', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Todos los miembros de la comunidad@es|||Participants@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Debate', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 1, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Debate', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 2, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Debate', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Encuesta', N'gnoss:hasestado', N'Estado@es|||State@en', 10006, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Encuesta', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10005, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Encuesta', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 0, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Encuesta', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 2, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Encuesta', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Grupo', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 0, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Grupo', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 1, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Mensaje', N'dce:type', N'Bandeja@es|||Box@en', 1, 1, 0, 1, 5, 8, 0, 2, 1, N'Bandeja@es|||Box@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Mensaje', N'nmo:from', N'Remitente@es|||From@en', 2, 0, 0, 1, 5, 8, 0, 2, 1, N'Remitente@es|||From@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Mensaje', N'nmo:isRead', N'Estado@es|||Status@en', 4, 0, 0, 1, 5, 8, 0, 0, 1, N'Estado@es|||Status@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Mensaje', N'nmo:sentDate', N'Fecha de envio@es|||Sending date@en', 6, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de envio@es|||Sending date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Mensaje', N'nmo:to', N'Destinatario@es|||To@en', 3, 0, 0, 1, 5, 8, 0, 2, 1, N'Destinatario@es|||To@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Mensaje', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 5, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Meta', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 1, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Meta', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 4, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Meta', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 3, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Organizacion', N'gnoss:hasfechaAlta', N'Fecha de alta@es|||Date of registration@en', 0, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de alta@es|||Date of registration@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Organizacion', N'oc:ProvinceOrState', N'Provincia@es|||Region@en', 10003, 0, 0, 1, 5, 8, 0, 1, 1, N'Provincia@es|||Region@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Organizacion', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 0, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Organizacion', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 1, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Organizacion', N'vcard:country-name', N'País@es|||Country@en|||País@pt', 2, 0, 0, 1, 5, 8, 0, 1, 1, N'País@es|||Country@en|||País@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Organizacion', N'vcard:locality', N'Localidad@es|||Location@en', 10004, 1, 0, 1, 5, 8, 0, 1, 1, N'Localidad@es|||Location@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'gnoss:hasEstadoCorreccion', N'Gestión de usuarios@es|||Users management@en', 0, 0, 0, 1, 5, 5, 0, 0, 1, N'Gestión de usuarios@es|||Users management@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'gnoss:hasfechaAlta', N'Fecha de alta@es|||Date of registration@en', 0, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de alta@es|||Date of registration@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'oc:ProvinceOrState', N'Provincia@es|||Region@en', 10003, 0, 0, 1, 5, 8, 0, 1, 1, N'Provincia@es|||Region@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 0, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 1, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'vcard:country-name', N'País@es|||Country@en|||País@pt', 10002, 0, 0, 1, 5, 8, 0, 1, 1, N'País@es|||Country@en|||País@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Persona', N'vcard:locality', N'Localidad@es|||Location@en', 10004, 1, 0, 1, 5, 8, 0, 1, 1, N'Localidad@es|||Location@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Pregunta', N'gnoss:hasestado', N'Estado@es|||State@en', 10006, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Pregunta', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10005, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Pregunta', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Todos los miembros de la comunidad@es|||Participants@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Pregunta', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 0, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Pregunta', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 2, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Pregunta', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Compartido', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:hasautor', N'Autores@es|||Authors@en', 10013, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:haseditor', N'Editores@es|||Editors@en', 10011, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:hasEstado', N'Estado@es|||State@en', 0, 0, 0, 1, 5, 4, 0, 0, 1, N'Estado@es|||State@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 10009, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 10006, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:hasparticipante', N'Lectores@es|||Lectors@en', 10012, 0, 0, 1, 5, 8, 0, 0, 1, N'Lectores@es|||Lectors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:haspublicador', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 1, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:haspublicadorMostrarCom', N'Personas@es|||People@en', 10004, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'gnoss:hastipodocExt', N'Tipo de documento@es|||Document class@en', 10008, 0, 0, 1, 5, 14, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'rdf:type', N'Tipo de contenido@es|||Item type@en', 10002, 1, 0, 1, 3, 11, 1, 3, 1, N'Tipo de contenido@es|||Item type@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'sioc:has_space', N'Comunidades@es|||Communities@en', 10003, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 10005, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Recurso Publicado', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:hasautor', N'Autores@es|||Authors@en', 9, 0, 0, 1, 5, 8, 0, 1, 1, N'Autores@es|||Authors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:haseditor', N'Editores@es|||Editors@en', 8, 0, 0, 1, 5, 8, 0, 1, 1, N'Editores@es|||Editors@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:hasEstadoPP', N'Estado@es|||Status@en', 0, 0, 0, 1, 5, 10, 0, 0, 1, N'Estado@es|||Status@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:hasextension', N'Extensión@es|||Extension@en', 5, 0, 0, 1, 5, 10, 0, 0, 1, N'Extensión@es|||Extension@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:hasfechapublicacion', N'Fecha de publicación@es|||Publishing date@en', 3, 0, 1, 0, 5, 6, 0, 0, 1, N'Fecha de publicación@es|||Publishing date@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:hasOrigen', N'Origen@es|||Origin@en', 0, 0, 0, 1, 5, 10, 0, 0, 1, N'Origen@es|||Origin@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:haspublicador', N'Publicadores@es|||Publishers@en', 7, 0, 0, 1, 5, 8, 0, 1, 1, N'Publicadores@es|||Publishers@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'gnoss:hastipodoc', N'Tipo de documento@es|||Document class@en', 4, 0, 0, 1, 5, 13, 0, 0, 1, N'Tipo de documento@es|||Document class@en', 1)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'sioc_t:Tag', N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 2, 0, 0, 1, 5, 8, 0, 0, 1, N'Etiquetas@es|||Tags@en|||Etiquetas@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'RecursoPerfilPersonal', N'skos:ConceptID', N'Categorías@es|||Categories@en|||Categorias@pt', 1, 0, 0, 1, 5, 0, 0, 0, 1, N'Categorías@es|||Categories@en|||Categorias@pt', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Suscripcion', N'dce:type', N'Espacio@es|||Space@en', 2, 1, 0, 1, 5, 8, 0, 2, 1, N'Espacio@es|||Space@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Suscripcion', N'foaf:familyName', N'Personas@es|||People@en', 4, 0, 0, 4, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Suscripcion', N'foaf:firstName', N'Personas@es|||People@en', 4, 0, 0, 1, 5, 8, 0, 0, 1, N'Personas@es|||People@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Suscripcion', N'gnoss:blogName', N'Blogs@es|||Blogs@en', 5, 0, 0, 1, 5, 8, 0, 0, 1, N'Blogs@es|||Blogs@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Suscripcion', N'gnoss:Estado', N'Estado@es|||Status@en', 1, 0, 0, 1, 5, 8, 0, 0, 1, N'Estado@es|||Status@en', 0)

INSERT [dbo].[FacetaObjetoConocimiento] ([ObjetoConocimiento], [Faceta], [Nombre], [Orden], [Autocompletar], [TipoPropiedad], [TipoDisenio], [ElementosVisibles], [AlgoritmoTransformacion], [EsSemantica], [Mayusculas], [EsPorDefecto], [NombreFaceta], [ComportamientoOr]) VALUES (N'Suscripcion', N'sioc:has_space', N'Comunidades@es|||Communities@en', 3, 0, 0, 1, 10, 1, 0, 0, 0, N'Comunidades@es|||Communities@en', 0)