<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	  <SonarQubeExclude>false</SonarQubeExclude>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Semiodesk.Trinity.Virtuoso" Version="1.0.3.77" />
		<!--Libreria transitiva de Semiodesk.Trinity.Virtuoso que tiene vulnerabilidades-->
		<PackageReference Include="System.Drawing.Common" Version="10.0.8" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Es.Riam.Gnoss.RabbitMQ\Es.Riam.Gnoss.RabbitMQ.csproj" />
    <ProjectReference Include="..\Es.Riam.Gnoss.Util\Es.Riam.Gnoss.Util.csproj" />
  </ItemGroup>

</Project>
