// <auto-generated />
using System;
using Es.Riam.Gnoss.AD.EntityModelBASE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Es.Riam.Gnoss.AD.Migrations.EntityContextBASEPostgresMigrations
{
    [DbContext(typeof(EntityContextBASEPostgres))]
    partial class EntityContextBASEPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreo", b =>
                {
                    b.Property<int>("CorreoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionRespuesta")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EnviadoRabbit")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsHtml")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsSeguro")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaPuestaEnCola")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HtmlTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MascaraDireccionRespuesta")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MascaraRemitente")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("Prioridad")
                        .HasColumnType("smallint");

                    b.Property<int>("Puerto")
                        .HasColumnType("integer");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SMTP")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.HasKey("CorreoID");

                    b.ToTable("ColaCorreo");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreoDestinatario", b =>
                {
                    b.Property<int>("CorreoID")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MascaraDestinatario")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("CorreoID", "Email");

                    b.ToTable("ColaCorreoDestinatario");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreoDestinatario", b =>
                {
                    b.HasOne("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreo", "ColaCorreo")
                        .WithMany("ColaCorreoDestinatario")
                        .HasForeignKey("CorreoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ColaCorreo");
                });

            modelBuilder.Entity("Es.Riam.Gnoss.AD.EntityModelBASE.Models.ColaCorreo", b =>
                {
                    b.Navigation("ColaCorreoDestinatario");
                });
#pragma warning restore 612, 618
        }
    }
}
